version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      torch-stack:
        patterns:
          - "torch"
          - "torchvision"
          - "torchaudio"
      pydantic-stack:
        patterns:
          - "pydantic"
          - "pydantic-core"
      fastapi-stack:
        patterns:
          - "starlette"
          - "fastapi"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"