version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"