name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Read version from VERSION file
      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      # Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Build the React frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      # Build and push the Python backend Docker image
      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wattbot:${{ env.VERSION }} -f backend.Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wattbot:${{ env.VERSION }}

      # Build and push the React frontend Docker image
      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wattbot-ui:${{ env.VERSION }} -f frontend.Dockerfile ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wattbot-ui:${{ env.VERSION }}